# Generated by Django 4.2.1 on 2023-06-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('dob', models.DateField()),
                ('aadhar', models.IntegerField(default=0)),
                ('bloodGrp', models.CharField(default='', max_length=3)),
                ('donationDate', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('contact', models.IntegerField(default=0)),
            ],
        ),
    ]
