# Generated by Django 4.2.1 on 2023-06-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_alter_donor_aadhar_alter_donor_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('dob', models.DateField()),
                ('aadhar', models.CharField(max_length=12)),
                ('bloodGrp', models.CharField(default='', max_length=3)),
                ('donationDate', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
    ]
